### ISSUE TITLE
Suggestions Box doesn't close when clicked

### ISSUE THREAD

**Issue by ChristianE00** [ChristianE00/equalizerExtension#18]
When the suggestion box's close button is clicked, it should simply disappear.

Currently it does not do anything when clicked.

![image](https://github.com/ChristianE00/AudioKit/assets/112213868/acd1677c-43de-40af-b2fd-0b7b04e1844f)

**Comment by satyammjha** [comment]
You can assign this to me. I can fix the issue.

**Comment by ChristianE00** [comment]
Sure, let me know if you have any issues.

**Comment by ChristianE00** [comment]
Implemented
