### ISSUE TITLE
Links not opening in a new tab when clicked on.

### ISSUE THREAD

**Issue by ChristianE00** [ChristianE00/equalizerExtension#8]
In the popup.html, the links don't open the links as intended unless you press ctrl + click.

**Comment by satyammjha** [comment]
> In the popup.html, the links don't open the links as intended unless you press ctrl + click.

I can fix this. You may assign this to me.

**Comment by srushtiss** [comment]
@ChristianE00 can you assign me this?

**Comment by ChristianE00** [comment]
Sure! Let me know if you have any questions.

**Comment by satyammjha** [comment]
I have fixed this.

**Comment by ChristianE00** [comment]
Thanks, your pull request has been merged. I really appreciate your help. 

I have added you to the list of contributors for the project:
https://christiane00.github.io/AudioKit.github.io/
